spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todolistdb
    username: kataolympp
    password: natixis
    driver-class-name: org.postgresql.Driver
  jooq:
    sql-dialect: POSTGRES
  sql:
    init:
      mode: always
  flyway:
    enabled: false # Disabling at application start, running with maven plugin instead