version: '3.9'

services:
  postgres-db:
    image: postgres:17.2
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: kataolympp
      POSTGRES_PASSWORD: natixis
      POSTGRES_DB: todolistdb
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # Base de données de test
  postgres-db-test:
    image: postgres:17.2
    container_name: postgres-db-test
    ports:
      - "5433:5432"  # Port local différent pour éviter les conflits
    environment:
      POSTGRES_USER: kataolympp
      POSTGRES_PASSWORD: natixis
      POSTGRES_DB: todolistdb_test
    volumes:
      - postgres-data-test:/var/lib/postgresql/data

volumes:
  postgres-data:
  postgres-data-test: